var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/logout/success/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0tyw8s~._.js")
R.c("server/chunks/ssr/0f-8_next_dist_0-n51ty._.js")
R.c("server/chunks/ssr/0f-8_next_dist_esm_build_templates_app-page_0na6or6.js")
R.c("server/chunks/ssr/[root-of-the-server]__0t00bqp._.js")
R.c("server/chunks/ssr/[root-of-the-server]__13gmbmx._.js")
R.c("server/chunks/ssr/next-auth_playground_src_03svtmk._.js")
R.c("server/chunks/ssr/next-auth_playground_0-9o649._.js")
R.c("server/chunks/ssr/0f-8_next_dist_client_components_03lo~5g._.js")
R.c("server/chunks/ssr/0f-8_next_dist_client_components_builtin_unauthorized_0-qopl~.js")
R.c("server/chunks/ssr/0f-8_next_dist_client_components_builtin_global-error_0mukumy.js")
R.c("server/chunks/ssr/0s8b_playground__next-internal_server_app_logout_success_page_actions_088kbp~.js")
R.m(22269)
module.exports=R.m(22269).exports
