var R=require("../chunks/ssr/[turbopack]_runtime.js")("server/app/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__04n2rq.._.js")
R.c("server/chunks/ssr/0f-8_next_dist_esm_build_templates_app-page_0ffzc2c.js")
R.c("server/chunks/ssr/next-auth_playground_0.xeblt._.js")
R.c("server/chunks/ssr/0f-8_next_dist_0-n51ty._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0t00bqp._.js")
R.c("server/chunks/ssr/[root-of-the-server]__13gmbmx._.js")
R.c("server/chunks/ssr/next-auth_playground_src_03svtmk._.js")
R.c("server/chunks/ssr/next-auth_playground_0-9o649._.js")
R.c("server/chunks/ssr/0f-8_next_dist_client_components_03lo~5g._.js")
R.c("server/chunks/ssr/0f-8_next_dist_client_components_builtin_unauthorized_0-qopl~.js")
R.c("server/chunks/ssr/0f-8_next_dist_client_components_builtin_global-error_0mukumy.js")
R.c("server/chunks/ssr/next-auth_playground__next-internal_server_app_page_actions_0ix8qcc.js")
R.m(86358)
module.exports=R.m(86358).exports
